int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int helper_sqrt(int n, int i);
int is_prime_number(int n);
int helper_f(int n, int i);
int _strlen_recursion(char *s);
int is_palindrome(char *s);
int helper(char *s, int length);
int wildcmp(char *s1, char *s2);
int findsrc(char *s, char c, int i, int p);
